#!/usr/bin/env python3
"""
Agent-Assembly-Line
"""
import os, sys
sys.path.append(os.path.join(os.path.dirname(__file__), '../'))

from agent_assembly_line.micros.diff_details_agent import DiffDetailsAgent
from agent_assembly_line.micros.diff_sum_agent import DiffSumAgent

if sys.stdin.isatty():
    if len(sys.argv) != 2:
        print("Usage: python diff_analysis.py <diff_text>")
        sys.exit(1)
    diff_text = sys.argv[1]
else:
    diff_text = sys.stdin.read()

agent = DiffDetailsAgent(diff_text)
detailed_answer = agent.run()


print("")
print(detailed_answer)
print("")
